---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-operator.html 
keywords: deploy, Trident, methods, operator, tridentctl, registry, registries 
summary: Sie kĂ¶nnen den Trident-Operator manuell bereitstellen, um Trident zu installieren. Dieser Prozess gilt fĂĽr Installationen, bei denen die von Trident benĂ¶tigten Container-Images nicht in einer privaten Registry gespeichert sind. 
---
= Manuelle Bereitstellung des Trident Operators (Standardmodus)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie kĂ¶nnen den Trident-Operator manuell bereitstellen, um Trident zu installieren. Dieser Prozess gilt fĂĽr Installationen, bei denen die von Trident benĂ¶tigten Container-Images nicht in einer privaten Registry gespeichert sind. Wenn Sie eine private Image-Registry haben, verwenden Sie die link:kubernetes-deploy-operator-mirror.html["Prozess fĂĽr die Offline-Bereitstellung"].



== Wichtige Informationen zu Trident 25.10

*Sie mĂĽssen die folgenden wichtigen Informationen ĂĽber Trident lesen.*

.<strong>Wichtige Informationen zu Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 wird jetzt in Trident unterstĂĽtzt. Aktualisieren Sie Trident, bevor Sie Kubernetes aktualisieren.
* Trident setzt die Verwendung der Multipathing-Konfiguration in SAN-Umgebungen strikt durch, mit einem empfohlenen Wert von  `find_multipaths: no` in der multipath.conf-Datei.
+
Die Verwendung einer Konfiguration ohne Multipathing oder die Verwendung von  `find_multipaths: yes` oder  `find_multipaths: smart` Wert in der Datei multipath.conf fĂĽhrt zu Mount-Fehlern. Trident hat die Verwendung von  `find_multipaths: no` seit der Version 21.07 empfohlen.



=====
====


== Den Trident-Operator manuell bereitstellen und Trident installieren

ĂśberprĂĽfen Sie link:../trident-get-started/kubernetes-deploy.html["die InstallationsĂĽbersicht"], um sicherzustellen, dass Sie die Installationsvoraussetzungen erfĂĽllt und die richtige Installationsoption fĂĽr Ihre Umgebung ausgewĂ¤hlt haben.

.Bevor Sie beginnen
Bevor Sie mit der Installation beginnen, melden Sie sich am Linux-Host an und vergewissern Sie sich, dass dieser ein funktionierendes link:requirements.html["unterstĂĽtzter Kubernetes-Cluster"^] verwaltet und dass Sie ĂĽber die erforderlichen Berechtigungen verfĂĽgen.


NOTE: Mit OpenShift verwenden Sie  `oc` statt  `kubectl` in allen folgenden Beispielen und melden Sie sich zuerst als *system:admin* an, indem Sie  `oc login -u system:admin` oder  `oc login -u kube-admin` ausfĂĽhren.

[%collapsible%open]
====
. ĂśberprĂĽfen Sie Ihre Kubernetes-Version:
+
[listing]
----
kubectl version
----
. ĂśberprĂĽfen Sie die Cluster-Administratorrechte:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. ĂśberprĂĽfen Sie, ob Sie einen Pod starten kĂ¶nnen, der ein Image von Docker Hub verwendet, und Ihr Speichersystem ĂĽber das Pod-Netzwerk erreichen kĂ¶nnen.
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


=== Schritt 1: Laden Sie das Trident-Installationspaket herunter

Das Trident-Installationspaket enthĂ¤lt alles, was Sie zum Bereitstellen des Trident-Operators und zum Installieren von Trident benĂ¶tigen. Laden Sie die neueste Version des Trident-Installationsprogramms von link:https://github.com/NetApp/trident/releases/latest["der Abschnitt _Assets_ auf GitHub"^] herunter und extrahieren Sie sie.

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v25.10.0/trident-installer-25.10.0.tar.gz
tar -xf trident-installer-25.10.0.tar.gz
cd trident-installer
----


=== Schritt 2: Erstellen Sie die `TridentOrchestrator` CRD

Erstellen Sie die `TridentOrchestrator` benutzerdefinierte Ressourcendefinition (CRD). Sie werden spĂ¤ter eine `TridentOrchestrator` benutzerdefinierte Ressource erstellen. Verwenden Sie die entsprechende CRD-YAML-Version in `deploy/crds`, um die `TridentOrchestrator` CRD zu erstellen.

[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----


=== Schritt 3: Den Trident Operator einsetzen

Das Trident-Installationsprogramm stellt eine Bundle-Datei bereit, mit der der Operator installiert und zugehĂ¶rige Objekte erstellt werden kĂ¶nnen. Die Bundle-Datei ist eine einfache MĂ¶glichkeit, den Operator bereitzustellen und Trident mit einer Standardkonfiguration zu installieren.

* FĂĽr Cluster, auf denen Kubernetes 1.24 lĂ¤uft, verwenden Sie `bundle_pre_1_25.yaml`.
* FĂĽr Cluster, auf denen Kubernetes 1.25 oder hĂ¶her lĂ¤uft, verwenden Sie `bundle_post_1_25.yaml`.


.Bevor Sie beginnen
* StandardmĂ¤Ăźig installiert das Trident-Installationsprogramm den Operator im  `trident` Namespace. Falls der  `trident` Namespace nicht existiert, erstellen Sie ihn mit:
+
[listing]
----
kubectl apply -f deploy/namespace.yaml
----
* Um den Operator in einem anderen Namespace als dem  `trident` Namespace bereitzustellen, aktualisieren Sie  `serviceaccount.yaml`, `clusterrolebinding.yaml` und  `operator.yaml` und generieren Sie Ihre Bundle-Datei mit dem  `kustomization.yaml`.
+
.. Erstellen Sie das  `kustomization.yaml` mit dem folgenden Befehl, wobei _<bundle.yaml>_  `bundle_pre_1_25.yaml` oder  `bundle_post_1_25.yaml` abhĂ¤ngig von Ihrer Kubernetes-Version ist.
+
[listing]
----
cp deploy/kustomization_<bundle.yaml> deploy/kustomization.yaml
----
.. Kompilieren Sie das Bundle mit dem folgenden Befehl, wobei _<bundle.yaml>_  `bundle_pre_1_25.yaml` oder  `bundle_post_1_25.yaml` entsprechend Ihrer Kubernetes-Version ist.
+
[listing]
----
kubectl kustomize deploy/ > deploy/<bundle.yaml>
----




.Schritte
. Erstellen Sie die Ressourcen und stellen Sie den Operator bereit:
+
[listing]
----
kubectl create -f deploy/<bundle.yaml>
----
. ĂśberprĂĽfen Sie, ob der Operator, die Bereitstellung und die ReplicaSets erstellt wurden.
+
[listing]
----
kubectl get all -n <operator-namespace>
----



IMPORTANT: Es sollte nur *eine Instanz* des Operators in einem Kubernetes-Cluster geben. Erstellen Sie nicht mehrere Deployments des Trident Operators.



=== Schritt 4: Erstellen Sie das `TridentOrchestrator` und installieren Sie Trident

Sie kĂ¶nnen jetzt die `TridentOrchestrator` erstellen und Trident installieren. Optional kĂ¶nnen Sie link:kubernetes-customize-deploy.html["Passen Sie Ihre Trident Installation individuell an"] mit den Attributen in der `TridentOrchestrator`-Spezifikation arbeiten.

[listing]
----
kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created

kubectl describe torc trident

Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Debug:     true
  Namespace: trident
  nodePrep:
  - iscsi
Status:
  Current Installation Params:
    IPv6:                      false
    Autosupport Hostname:
    Autosupport Image:         netapp/trident-autosupport:25.10
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                     true
    Image Pull Secrets:
    Image Registry:
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Silence Autosupport:  false
    Trident Image:        netapp/trident:25.10.0
  Message:                  Trident installed  Namespace:                trident
  Status:                   Installed
  Version:                  v25.10.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----


== ĂśberprĂĽfen Sie die Installation

Es gibt mehrere MĂ¶glichkeiten, Ihre Installation zu ĂĽberprĂĽfen.



=== Status mit  `TridentOrchestrator` verwenden

Der Status von `TridentOrchestrator` zeigt an, ob die Installation erfolgreich war und zeigt die installierte Version von Trident an. WĂ¤hrend der Installation Ă¤ndert sich der Status von `TridentOrchestrator` `Installing` zu `Installed`. Wenn Sie den `Failed` Status beobachten und der Operator das Problem nicht selbst beheben kann, link:../troubleshooting.html["ĂśberprĂĽfen Sie die Protokolle"].

[cols="2"]
|===
| Status | Beschreibung 


| Installation | Der Operator installiert Trident mit diesem  `TridentOrchestrator` CR. 


| Installiert | Trident wurde erfolgreich installiert. 


| Deinstallation | Der Betreiber deinstalliert Trident, weil
`spec.uninstall=true`. 


| Deinstalliert | Trident ist deinstalliert. 


| Fehlgeschlagen | Der Operator konnte Trident nicht installieren, patchen, aktualisieren oder deinstallieren; der Operator wird automatisch versuchen, sich von diesem Zustand zu erholen. Wenn dieser Zustand weiterhin besteht, ist eine Fehlerbehebung erforderlich. 


| Aktualisierung | Der Betreiber aktualisiert eine bestehende Installation. 


| Fehler | Das `TridentOrchestrator` wird nicht verwendet. Ein anderer existiert bereits. 
|===


=== Verwendung des Pod-Erstellungsstatus

Sie kĂ¶nnen bestĂ¤tigen, ob die Trident Installation abgeschlossen wurde, indem Sie den Status der erstellten Pods ĂĽberprĂĽfen:

[listing]
----
kubectl get pods -n trident

NAME                                       READY   STATUS    RESTARTS   AGE
trident-controller-7d466bf5c7-v4cpw        6/6     Running   0           1m
trident-node-linux-mr6zc                   2/2     Running   0           1m
trident-node-linux-xrp7w                   2/2     Running   0           1m
trident-node-linux-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv          1/1     Running   0           3m
----


=== Verwendung `tridentctl`

Sie kĂ¶nnen  `tridentctl` verwenden, um die installierte Version von Trident zu ĂĽberprĂĽfen.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.10.0        | 25.10.0        |
+----------------+----------------+
----